title: "JOI 印象に残っている問題 投票結果"
description: "日本情報オリンピックの印象に残っている問題の投票結果"
baseurl: "/joi-problem-votes"
url: "https://blue-jam.github.io"
lang: ja
theme: minima

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude from processing
exclude:
  - "*.py"
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github
